/* ============================================================================
   app.js  —  rendering engine for the HNCTech editable template
   ----------------------------------------------------------------------------
   Reads everything from `siteConfig` (site-config.js) and renders it into the
   skeleton in index.html. You normally do not edit this file — change content
   in site-config.js, or use the Theme Customizer (gear button, bottom-right).
   ============================================================================ */
(function () {
  "use strict";

  const cfg = window.siteConfig;
  const LS_KEY = "hnctech_theme_overrides";
  const CONTENT_KEY = "hnctech_content";
  const $  = (sel) => document.querySelector(sel);
  const $$ = (sel) => Array.from(document.querySelectorAll(sel));

  /* ---------------------------------------------------------- COLOR HELPERS */
  function clamp(n) { return Math.max(0, Math.min(255, Math.round(n))); }
  function hexToRgb(hex) {
    const h = hex.replace("#", "");
    const v = h.length === 3 ? h.split("").map((c) => c + c).join("") : h;
    return { r: parseInt(v.slice(0, 2), 16), g: parseInt(v.slice(2, 4), 16), b: parseInt(v.slice(4, 6), 16) };
  }
  function rgbToHex(r, g, b) {
    return "#" + [r, g, b].map((x) => clamp(x).toString(16).padStart(2, "0")).join("");
  }
  function mixBlack(hex, amt) { const c = hexToRgb(hex); const k = 1 - amt; return rgbToHex(c.r * k, c.g * k, c.b * k); }
  function mixWhite(hex, amt) { const c = hexToRgb(hex); return rgbToHex(c.r + (255 - c.r) * amt, c.g + (255 - c.g) * amt, c.b + (255 - c.b) * amt); }

  /* ------------------------------------------------------------- THEME/SEO */
  function loadSavedTheme() {
    try { return JSON.parse(localStorage.getItem(LS_KEY)) || {}; } catch (e) { return {}; }
  }
  function saveTheme(overrides) {
    try { localStorage.setItem(LS_KEY, JSON.stringify(overrides)); } catch (e) {}
  }

  /* ---------------------------------------- EDITABLE CONTENT (Option B) */
  function loadContent() {
    try { return JSON.parse(localStorage.getItem(CONTENT_KEY)) || {}; } catch (e) { return {}; }
  }
  function saveContent(obj) {
    try {
      if (obj === null) localStorage.removeItem(CONTENT_KEY);
      else localStorage.setItem(CONTENT_KEY, JSON.stringify(obj));
    } catch (e) {}
  }
  // Overlay any browser-saved edits on top of the defaults in site-config.js
  function applyContentOverrides() {
    const saved = loadContent();
    if (Array.isArray(saved.services))     cfg.services.items     = saved.services;
    if (Array.isArray(saved.projects))     cfg.projects.items     = saved.projects;
    if (Array.isArray(saved.testimonials)) cfg.testimonials.items = saved.testimonials;
  }

  function loadFonts(display, body) {
    const fam = (name) => name.trim().replace(/\s+/g, "+") + ":wght@400;500;600;700";
    const url = "https://fonts.googleapis.com/css2?family=" + fam(display) + "&family=" + fam(body) + "&display=swap";
    $("#font-link").setAttribute("href", url);
  }

  function applyTheme(theme) {
    const root = document.documentElement.style;
    root.setProperty("--c-primary", theme.primaryColor);
    root.setProperty("--c-primary-deep", mixBlack(theme.primaryColor, 0.30));
    root.setProperty("--c-primary-soft", mixWhite(theme.primaryColor, 0.12));
    root.setProperty("--c-secondary", theme.secondaryColor);
    root.setProperty("--c-accent", theme.accentColor);
    root.setProperty("--c-bg", theme.bgColor);
    root.setProperty("--c-text", theme.textColor);
    root.setProperty("--font-display", `"${theme.fontDisplay}", system-ui, sans-serif`);
    root.setProperty("--font-body", `"${theme.fontBody}", system-ui, sans-serif`);
    loadFonts(theme.fontDisplay, theme.fontBody);
  }

  function applySeo(seo) {
    document.title = seo.title;
    $("#meta-description").setAttribute("content", seo.description);
    $("#meta-keywords").setAttribute("content", seo.keywords || "");
    $("#og-title").setAttribute("content", seo.title);
    $("#og-description").setAttribute("content", seo.description);
    if (seo.ogImage) $("#og-image").setAttribute("content", seo.ogImage);

    const ld = {
      "@context": "https://schema.org",
      "@type": "Organization",
      "name": cfg.brand.legalName || cfg.brand.companyName,
      "url": seo.url || "",
      "description": seo.description,
      "address": { "@type": "PostalAddress", "addressLocality": cfg.contact.address },
      "email": cfg.contact.email,
      "telephone": cfg.contact.phone
    };
    if (seo.ogImage) ld.logo = seo.ogImage;
    $("#ld-json").textContent = JSON.stringify(ld, null, 2);
  }

  // Set the browser-tab icon (favicon) and the iOS home-screen icon from config.
  function applyFavicon(brand) {
    if (!brand || !brand.favicon) return;
    const ensure = (rel) => {
      let link = document.querySelector(`link[rel="${rel}"]`);
      if (!link) { link = document.createElement("link"); link.setAttribute("rel", rel); document.head.appendChild(link); }
      return link;
    };
    const icon = ensure("icon");
    icon.setAttribute("href", brand.favicon);
    if (/\.png$/i.test(brand.favicon)) icon.setAttribute("type", "image/png");
    else if (/\.svg$/i.test(brand.favicon)) icon.setAttribute("type", "image/svg+xml");
    else if (/\.ico$/i.test(brand.favicon)) icon.setAttribute("type", "image/x-icon");
    ensure("apple-touch-icon").setAttribute("href", brand.favicon);
  }

  /* --------------------------------------------------------- SMALL BUILDERS */
  function brandMarkup() {
    const b = cfg.brand;
    // If a full logo image is provided, use it as the ENTIRE brand block.
    // (The PNG typically already contains the company name, so we don't repeat it.)
    if (b.logoImage) {
      return `<img class="brand-img" src="${b.logoImage}" alt="${b.companyName || b.legalName || "Logo"}">`;
    }
    // Fallback: stylised "mark + text" lockup using initial + tagline.
    const mark = `<span class="mark">${b.logoText || b.companyName.charAt(0)}</span>`;
    const name = b.companyName.split(" ")[0] || b.companyName;
    return `${mark}<span>${name}<span class="tagline">${b.tagline || ""}</span></span>`;
  }

  /* ----------------------------------------------------------------- RENDER */
  function renderNav() {
    $("#navBrand").innerHTML = brandMarkup();
    const links = cfg.nav.links.map((l) =>
      `<li class="nav-item"><a class="nav-link" href="${l.href}">${l.label}</a></li>`).join("");
    const cta = `<li class="nav-item ms-lg-3 mt-2 mt-lg-0"><a class="btn btn-cyan" href="${cfg.nav.ctaHref}">${cfg.nav.ctaLabel}</a></li>`;
    $("#navLinks").innerHTML = links + cta;
    const first = $("#navLinks .nav-link");
    if (first) first.classList.add("active");
  }

  function renderHero() {
    const h = cfg.hero;
    if (h.image) {
      const img = $("#heroBgImg");
      img.src = h.image; img.hidden = false;
    }
    if (!h.showParticles) { const c = $("#network-canvas"); if (c) c.style.display = "none"; }
    const badges = (h.badges || []).map((b) =>
      `<span class="hero-badge"><i class="bi ${b.icon}"></i> ${b.text}</span>`).join("");
    $("#heroContent").innerHTML = `
      <div class="row"><div class="col-lg-9">
        <span class="eyebrow light">${h.eyebrow}</span>
        <h1>${h.title} <span class="accent">${h.titleAccent}</span></h1>
        <p class="sub">${h.subtitle}</p>
        <div class="d-flex flex-wrap gap-3">
          <a href="${h.primaryBtn.href}" class="btn btn-cyan btn-lg">${h.primaryBtn.label} <i class="bi bi-arrow-right ms-1"></i></a>
          <a href="${h.secondaryBtn.href}" class="btn btn-ghost btn-lg">${h.secondaryBtn.label}</a>
        </div>
        <div class="hero-badges">${badges}</div>
      </div></div>`;
  }

  function renderAbout() {
    const a = cfg.about;
    const imgs = Array.isArray(a.images) ? a.images.filter(Boolean) : [];
    let visual;
    if (imgs.length > 1) {
      // multiple images → fading slideshow
      const slides = imgs.map((src, i) =>
        `<img class="about-slide${i === 0 ? " active" : ""}" src="${src}" alt="${cfg.brand.companyName}" loading="lazy" decoding="async">`).join("");
      visual = `<div class="about-visual"><div class="about-slides" id="aboutSlides">${slides}</div>${floatCard(a.floatCard)}</div>`;
    } else if (imgs[0] || a.image) {
      // single image (from images[] or the legacy image field)
      visual = `<div class="about-visual"><img class="cover" src="${imgs[0] || a.image}" alt="${cfg.brand.companyName}" loading="lazy" decoding="async">${floatCard(a.floatCard)}</div>`;
    } else {
      // no image → built-in rack visual
      visual = `<div class="about-visual"><div class="rack">${"<span></span>".repeat(8)}</div>${floatCard(a.floatCard)}</div>`;
    }
    const paras = a.paragraphs.map((p, i) =>
      `<p class="${i === 0 ? "lead-sub mb-3" : "text-grey mb-4"}">${p}</p>`).join("");
    const stats = a.stats.map((s) => `
      <div class="col-6 col-md-3">
        <div class="stat-card">
          <div class="stat-num" data-count="${s.value}">0<span class="plus">${s.suffix}</span></div>
          <div class="stat-label">${s.label}</div>
        </div>
      </div>`).join("");
    $("#aboutContainer").innerHTML = `
      <div class="row align-items-center g-5">
        <div class="col-lg-6 reveal">${visual}</div>
        <div class="col-lg-6 reveal">
          <div class="section-head">
            <span class="eyebrow">${a.eyebrow}</span>
            <h2>${a.heading}</h2>
          </div>
          ${paras}
          <div class="row g-3">${stats}</div>
        </div>
      </div>`;
  }
  function floatCard(f) {
    if (!f) return "";
    return `<div class="about-float"><div class="ic"><i class="bi ${f.icon}"></i></div>
      <div><div style="font-weight:600;">${f.title}</div>
      <div style="font-size:.82rem; color:rgba(255,255,255,0.6);">${f.text}</div></div></div>`;
  }

  function sectionHead(eyebrow, heading, subtitle, light) {
    const sub = subtitle ? `<p class="lead-sub mx-auto">${subtitle}</p>` : "";
    return `<div class="section-head center reveal mb-5">
      <span class="eyebrow${light ? " light" : ""}">${eyebrow}</span>
      <h2>${heading}</h2>${sub}</div>`;
  }

  function renderServices() {
    const s = cfg.services;
    const cards = s.items.map((it) => `
      <div class="col-md-6 col-lg-4 reveal">
        <div class="service-card">
          <div class="service-ic"><i class="bi ${it.icon}"></i></div>
          <h5>${it.title}</h5>
          <p>${it.description}</p>
          <a href="${it.link || "#contact"}" class="learn-more">Learn more <i class="bi bi-arrow-right"></i></a>
        </div>
      </div>`).join("");
    $("#servicesContainer").innerHTML = sectionHead(s.eyebrow, s.heading, s.subtitle) + `<div class="row g-4">${cards}</div>`;
  }

  function renderSolutions() {
    const s = cfg.solutions;
    const cards = s.items.map((it) => `
      <div class="col-sm-6 col-lg-3 reveal">
        <div class="sol-card"><i class="bi ${it.icon} head-ic"></i><h5>${it.title}</h5><p>${it.description}</p></div>
      </div>`).join("");
    $("#solutionsContainer").innerHTML = sectionHead(s.eyebrow, s.heading, s.subtitle) + `<div class="row g-4">${cards}</div>`;
  }

  function renderWhy() {
    const w = cfg.why;
    const features = w.features.map((f) => `
      <div class="feature-row">
        <div class="feature-ic"><i class="bi ${f.icon}"></i></div>
        <div><h5>${f.title}</h5><p>${f.text}</p></div>
      </div>`).join("");
    const sig = w.signature;
    const sigItems = sig.items.map((i) => `<li><i class="bi bi-check2-circle"></i> ${i}</li>`).join("");
    $("#whyContainer").innerHTML = `
      <div class="row g-5 align-items-start">
        <div class="col-lg-6 reveal">
          <div class="section-head">
            <span class="eyebrow light">${w.eyebrow}</span>
            <h2>${w.heading}</h2>
            <p class="lead-sub">${w.subtitle}</p>
          </div>
          <div class="mt-4">${features}</div>
        </div>
        <div class="col-lg-6 reveal">
          <div class="doc-panel">
            <span class="tag">${sig.tag}</span>
            <h3>${sig.title}</h3>
            <p style="color:rgba(255,255,255,0.65); font-size:.95rem;">${sig.text}</p>
            <ul class="doc-list">${sigItems}</ul>
          </div>
        </div>
      </div>`;
  }

  function renderIndustries() {
    const ind = cfg.industries;
    const cards = ind.items.map((it) => `
      <div class="col-6 col-md-3 reveal">
        <div class="ind-card"><i class="bi ${it.icon}"></i><span>${it.label}</span></div>
      </div>`).join("");
    $("#industriesContainer").innerHTML = sectionHead(ind.eyebrow, ind.heading) + `<div class="row g-4">${cards}</div>`;
  }

  function renderProjects() {
    const p = cfg.projects;
    const filters = p.filters.map((f, i) =>
      `<button class="filter-btn${i === 0 ? " active" : ""}" data-filter="${f.key}">${f.label}</button>`).join("");
    const cards = p.items.map((it) => {
      const thumb = it.image
        ? `<div class="proj-thumb"><img class="cover" src="${it.image}" alt="${it.title}" loading="lazy" decoding="async"><span class="proj-cat">${it.categoryLabel}</span></div>`
        : `<div class="proj-thumb"><div class="ovl"></div><span class="proj-cat">${it.categoryLabel}</span><i class="bi ${it.icon}"></i></div>`;
      const tech = (it.tech || []).map((t) => `<span>${t}</span>`).join("");
      return `
      <div class="col-md-6 col-lg-4 proj-item reveal" data-cat="${it.category}">
        <div class="proj-card">
          ${thumb}
          <div class="proj-body">
            <h5>${it.title}</h5>
            <div class="proj-meta"><i class="bi bi-geo-alt"></i> ${it.location}</div>
            <p class="proj-desc">${it.description}</p>
            <div class="proj-tech">${tech}</div>
          </div>
        </div>
      </div>`;
    }).join("");
    $("#projectsContainer").innerHTML =
      `<div class="section-head center reveal"><span class="eyebrow">${p.eyebrow}</span><h2>${p.heading}</h2></div>
       <div class="filter-btns reveal">${filters}</div>
       <div class="row g-4" id="projectGrid">${cards}</div>`;
  }

  function renderPartners() {
    const p = cfg.partners;
    const chip = (it) => it.logo
      ? `<span class="logo-chip"><img src="${it.logo}" alt="${it.name}" loading="lazy"></span>`
      : `<span class="logo-chip"><i class="bi ${it.icon}"></i> ${it.name}</span>`;
    const chips = p.items.map(chip).join("");
    $("#partnersContainer").innerHTML = `
      <div class="container text-center">
        <span class="eyebrow reveal" style="justify-content:center; display:flex;">${p.eyebrow}</span>
        <p class="text-grey mt-3 mb-4 reveal">${p.subtitle}</p>
      </div>
      <div class="logo-strip reveal"><div class="logo-track" id="logoTrack">${chips}</div></div>`;
  }

  function renderTestimonials() {
    const t = cfg.testimonials;
    const slides = t.items.map((it) => {
      const avatar = it.photo
        ? `<div class="testi-avatar"><img src="${it.photo}" alt="${it.name}" loading="lazy"></div>`
        : `<div class="testi-avatar">${it.initials || it.name.charAt(0)}</div>`;
      return `
      <div class="testi-slide"><div class="testi-card">
        <i class="bi bi-quote quote-ic"></i>
        <p class="body">${it.quote}</p>
        <div class="testi-author">${avatar}
          <div><div class="name">${it.name}</div><div class="role">${it.role}</div></div>
        </div>
      </div></div>`;
    }).join("");
    $("#testimonialsContainer").innerHTML =
      sectionHead(t.eyebrow, t.heading, null, true) +
      `<div class="reveal testi-viewport"><div class="testi-track" id="testiTrack">${slides}</div>
       <div class="testi-nav" id="testiNav"></div></div>`;
  }

  function renderContact() {
    const c = cfg.contact;
    const opts = c.serviceOptions.map((o) => `<option>${o}</option>`).join("");
    const map = c.mapEmbedUrl
      ? `<div class="map-embed"><iframe src="${c.mapEmbedUrl}" title="Map" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div>`
      : `<div class="map-embed"><div class="text-center"><i class="bi bi-pin-map-fill d-block mb-2"></i>Add a Google Maps embed URL in site-config.js</div></div>`;
    $("#contactContainer").innerHTML =
      sectionHead(c.eyebrow, c.heading, c.subtitle) + `
      <div class="row g-4">
        <div class="col-lg-7 reveal"><div class="contact-card"><div class="row g-3">
          <div class="col-md-6"><label class="form-label">Full Name *</label><input type="text" class="form-control" id="cName" placeholder="Your name"></div>
          <div class="col-md-6"><label class="form-label">Company</label><input type="text" class="form-control" id="cCompany" placeholder="Company name"></div>
          <div class="col-md-6"><label class="form-label">Email *</label><input type="email" class="form-control" id="cEmail" placeholder="you@company.com"></div>
          <div class="col-md-6"><label class="form-label">Phone</label><input type="tel" class="form-control" id="cPhone" placeholder="+91"></div>
          <div class="col-12"><label class="form-label">Service Required</label>
            <select class="form-select" id="cService"><option selected disabled>Select a service</option>${opts}</select></div>
          <div class="col-12"><label class="form-label">Message</label>
            <textarea class="form-control" id="cMessage" rows="4" placeholder="Brief about your requirement, site location and timeline"></textarea></div>
          <div class="col-12">
            <button type="button" class="btn btn-royal btn-lg w-100" id="contactSubmit">Send Enquiry <i class="bi bi-send ms-1"></i></button>
            <div id="formNote" class="text-grey mt-2" style="font-size:.82rem; display:none;"></div>
          </div>
        </div></div></div>
        <div class="col-lg-5 reveal"><div class="contact-info-card">
          <h3>${cfg.brand.legalName || cfg.brand.companyName}</h3>
          <p style="color:rgba(255,255,255,0.6); font-size:.92rem;">IT Infrastructure &amp; System Integration</p>
          <div class="mt-3">
            <div class="info-row"><div class="ic"><i class="bi bi-geo-alt-fill"></i></div><div><div class="lbl">Location</div><div class="val">${c.address}</div></div></div>
            <div class="info-row"><div class="ic"><i class="bi bi-envelope-fill"></i></div><div><div class="lbl">Email</div><a class="val" href="mailto:${c.email}">${c.email}</a></div></div>
            <div class="info-row"><div class="ic"><i class="bi bi-telephone-fill"></i></div><div><div class="lbl">Phone</div><a class="val" href="tel:${c.phone.replace(/\s+/g, "")}">${c.phone}</a></div></div>
            <div class="info-row"><div class="ic"><i class="bi bi-globe2"></i></div><div><div class="lbl">Website</div><a class="val" href="${c.websiteUrl || "#"}" target="_blank" rel="noopener">${c.website}</a></div></div>
          </div>
          ${map}
        </div></div>
      </div>`;
  }

  function renderFooter() {
    const f = cfg.footer;
    const social = f.social.map((s) =>
      `<a href="${s.href}" aria-label="${s.label}"><i class="bi ${s.icon}"></i></a>`).join("");
    const cols = f.columns.map((col) => {
      const links = col.links.map((l) => `<a href="${l.href}">${l.label}</a>`).join("<br>");
      return `<div class="col-6 col-lg-2"><h6>${col.title}</h6>${links}</div>`;
    }).join("");
    const c = cfg.contact;
    $("#footerContainer").innerHTML = `
      <div class="row g-4">
        <div class="col-lg-4">
          <a class="brand-logo mb-3" href="#home">${brandMarkup()}</a>
          <p style="font-size:.9rem; max-width:300px;">${f.about}</p>
          <div class="footer-social">${social}</div>
        </div>
        ${cols}
        <div class="col-lg-4">
          <h6>Contact</h6>
          <p style="font-size:.9rem; margin:0;"><i class="bi bi-geo-alt me-2"></i>${c.address}</p>
          <p style="font-size:.9rem; margin:6px 0 0;"><i class="bi bi-envelope me-2"></i>${c.email}</p>
          <p style="font-size:.9rem; margin:6px 0 0;"><i class="bi bi-globe2 me-2"></i>${c.website}</p>
        </div>
      </div>
      <div class="footer-bottom d-flex flex-column flex-md-row justify-content-between align-items-center gap-2">
        <span>${f.copyright}</span>
        <span class="text-grey">${f.legal || ""}</span>
      </div>`;
  }

  /* ------------------------------------------------------------ INTERACTIONS */
  function bindProjectFilters() {
    const filterBtns = $$(".filter-btn");
    const projItems = $$(".proj-item");
    filterBtns.forEach((btn) => {
      btn.addEventListener("click", () => {
        filterBtns.forEach((b) => b.classList.remove("active"));
        btn.classList.add("active");
        const f = btn.dataset.filter;
        projItems.forEach((item) => { item.style.display = (f === "all" || item.dataset.cat === f) ? "" : "none"; });
      });
    });
  }

  // Make freshly-rendered .reveal elements visible immediately (no scroll wait)
  function revealNow(scope) { (scope || document).querySelectorAll(".reveal").forEach((el) => el.classList.add("in")); }

  // Re-render a single editable section live and re-bind its interactions.
  function refreshSection(name) {
    if (name === "services") { renderServices(); revealNow($("#servicesContainer")); }
    else if (name === "projects") { renderProjects(); revealNow($("#projectsContainer")); bindProjectFilters(); }
    else if (name === "testimonials") { renderTestimonials(); revealNow($("#testimonialsContainer")); initTestimonials(); }
  }

  function initInteractions() {
    // Navbar scroll state
    const nav = $("#mainNav");
    const onScroll = () => nav.classList.toggle("scrolled", window.scrollY > 40);
    onScroll();
    window.addEventListener("scroll", onScroll, { passive: true });

    // Close mobile menu on link click
    $$("#navMenu .nav-link, #navMenu .btn").forEach((link) => {
      link.addEventListener("click", () => {
        const collapse = bootstrap.Collapse.getInstance($("#navMenu"));
        if (collapse && window.innerWidth < 992) collapse.hide();
      });
    });

    // Active nav link on scroll
    const navLinks = $$("#navMenu .nav-link");
    const navObserver = new IntersectionObserver((entries) => {
      entries.forEach((e) => {
        if (e.isIntersecting) {
          const id = e.target.id;
          navLinks.forEach((l) => l.classList.toggle("active", l.getAttribute("href") === "#" + id));
        }
      });
    }, { rootMargin: "-45% 0px -50% 0px" });
    $$("section[id], header[id]").forEach((s) => navObserver.observe(s));

    // Reveal on scroll
    const revealObserver = new IntersectionObserver((entries) => {
      entries.forEach((e) => { if (e.isIntersecting) { e.target.classList.add("in"); revealObserver.unobserve(e.target); } });
    }, { threshold: 0.12 });
    $$(".reveal").forEach((el) => revealObserver.observe(el));

    // Animated counters
    const counterObserver = new IntersectionObserver((entries) => {
      entries.forEach((e) => {
        if (!e.isIntersecting) return;
        const el = e.target;
        const target = +el.dataset.count;
        const plus = el.querySelector(".plus") ? el.querySelector(".plus").outerHTML : "";
        let cur = 0;
        const step = Math.max(1, Math.round(target / 60));
        const tick = () => {
          cur += step;
          if (cur >= target) el.innerHTML = target + plus;
          else { el.innerHTML = cur + plus; requestAnimationFrame(tick); }
        };
        tick();
        counterObserver.unobserve(el);
      });
    }, { threshold: 0.5 });
    $$(".stat-num[data-count]").forEach((c) => counterObserver.observe(c));

    // Project filter
    bindProjectFilters();

    // Seamless logo marquee (duplicate track)
    const track = $("#logoTrack");
    if (track) track.innerHTML += track.innerHTML;

    // Testimonials slider
    initTestimonials();

    // Contact form (front-end demo)
    const submit = $("#contactSubmit");
    if (submit) {
      submit.addEventListener("click", () => {
        const name = $("#cName").value.trim();
        const email = $("#cEmail").value.trim();
        const note = $("#formNote");
        note.style.display = "block";
        if (!name || !email) { note.style.color = "#c0392b"; note.textContent = "Please enter at least your name and email."; return; }
        note.style.color = "#1e7e34";
        note.textContent = "Thanks, " + name + ". This is a demo form — connect it to your email or CRM backend to receive enquiries.";
      });
    }

    // Hero network animation
    initNetworkCanvas();

    // About images slideshow (only runs when about.images has 2+ entries)
    initAboutSlideshow();
  }

  function initAboutSlideshow() {
    const wrap = $("#aboutSlides");
    if (!wrap) return;
    const slides = Array.from(wrap.querySelectorAll(".about-slide"));
    if (slides.length < 2) return;
    let i = 0;
    setInterval(() => {
      slides[i].classList.remove("active");
      i = (i + 1) % slides.length;
      slides[i].classList.add("active");
    }, 3500); // milliseconds per image — increase to slow down
  }

  let testiTimer = null;
  function initTestimonials() {
    const tTrack = $("#testiTrack");
    if (!tTrack) return;
    if (testiTimer) { clearInterval(testiTimer); testiTimer = null; }
    const slides = tTrack.children.length;
    const tNav = $("#testiNav");
    let tIndex = 0;
    for (let i = 0; i < slides; i++) {
      const dot = document.createElement("button");
      dot.className = "testi-dot" + (i === 0 ? " active" : "");
      dot.setAttribute("aria-label", "Go to testimonial " + (i + 1));
      dot.addEventListener("click", () => { goTo(i); restart(); });
      tNav.appendChild(dot);
    }
    const dots = Array.from(tNav.children);
    function goTo(i) {
      tIndex = i;
      tTrack.style.transform = `translateX(-${i * 100}%)`;
      dots.forEach((d, di) => d.classList.toggle("active", di === i));
    }
    function restart() { if (testiTimer) clearInterval(testiTimer); testiTimer = setInterval(() => goTo((tIndex + 1) % slides), 6000); }
    if (slides > 1) restart();
  }

  function initNetworkCanvas() {
    const canvas = $("#network-canvas");
    if (!canvas || canvas.style.display === "none") return;
    const ctx = canvas.getContext("2d");
    const reduce = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    const DPR = Math.min(window.devicePixelRatio || 1, 2);
    let w, h, nodes, raf;

    // Pull accent color from the live theme so the animation always matches.
    const accent = getComputedStyle(document.documentElement).getPropertyValue("--c-accent").trim() || "#00D4FF";
    const rgb = hexToRgb(accent);
    const lineRGB = `${rgb.r},${rgb.g},${rgb.b}`;
    const dotColor = rgbToHex(Math.min(255, rgb.r + 80), Math.min(255, rgb.g + 30), 255);

    function resize() {
      w = canvas.clientWidth; h = canvas.clientHeight;
      canvas.width = w * DPR; canvas.height = h * DPR;
      ctx.setTransform(DPR, 0, 0, DPR, 0, 0);
      const count = Math.min(90, Math.floor(w / 16));
      nodes = Array.from({ length: count }, () => ({
        x: Math.random() * w, y: Math.random() * h,
        vx: (Math.random() - 0.5) * 0.35, vy: (Math.random() - 0.5) * 0.35
      }));
    }
    function draw() {
      ctx.clearRect(0, 0, w, h);
      for (const n of nodes) {
        n.x += n.vx; n.y += n.vy;
        if (n.x < 0 || n.x > w) n.vx *= -1;
        if (n.y < 0 || n.y > h) n.vy *= -1;
      }
      for (let i = 0; i < nodes.length; i++) {
        for (let j = i + 1; j < nodes.length; j++) {
          const a = nodes[i], b = nodes[j];
          const dist = Math.hypot(a.x - b.x, a.y - b.y);
          if (dist < 130) {
            ctx.strokeStyle = `rgba(${lineRGB},${(1 - dist / 130) * 0.5})`;
            ctx.lineWidth = 0.7;
            ctx.beginPath(); ctx.moveTo(a.x, a.y); ctx.lineTo(b.x, b.y); ctx.stroke();
          }
        }
      }
      for (const n of nodes) {
        ctx.beginPath(); ctx.arc(n.x, n.y, 1.8, 0, Math.PI * 2);
        ctx.fillStyle = dotColor; ctx.fill();
      }
      raf = requestAnimationFrame(draw);
    }
    function start() {
      resize();
      if (!reduce) draw();
      else { ctx.clearRect(0, 0, w, h); for (const n of nodes) { ctx.beginPath(); ctx.arc(n.x, n.y, 1.8, 0, Math.PI * 2); ctx.fillStyle = dotColor; ctx.fill(); } }
    }
    window.addEventListener("resize", () => { cancelAnimationFrame(raf); start(); });
    start();
  }

  /* ------------------------------------------------------ THEME CUSTOMIZER */
  function buildThemeCustomizer(activeTheme) {
    const fontChoices = ["Space Grotesk", "Inter", "Poppins", "Montserrat", "Sora", "Manrope", "Plus Jakarta Sans", "Roboto", "Lato", "Work Sans"];
    const fontOpts = (sel) => fontChoices.map((f) => `<option ${f === sel ? "selected" : ""}>${f}</option>`).join("");

    $("#themeCustomizer").innerHTML = `
      <button class="tc-toggle" id="tcToggle" aria-label="Customize theme"><i class="bi bi-palette-fill"></i></button>
      <div class="tc-panel" id="tcPanel">
        <h6>Theme Customizer</h6>
        <div class="tc-sub">Live preview · saved to this browser</div>
        <div class="tc-field"><label>Primary</label><input type="color" id="tcPrimary" value="${activeTheme.primaryColor}"></div>
        <div class="tc-field"><label>Secondary</label><input type="color" id="tcSecondary" value="${activeTheme.secondaryColor}"></div>
        <div class="tc-field"><label>Accent</label><input type="color" id="tcAccent" value="${activeTheme.accentColor}"></div>
        <div class="tc-field"><label>Background</label><input type="color" id="tcBg" value="${activeTheme.bgColor}"></div>
        <div class="tc-field"><label>Text</label><input type="color" id="tcText" value="${activeTheme.textColor}"></div>
        <div class="tc-field"><label>Headings font</label><select id="tcFontDisplay">${fontOpts(activeTheme.fontDisplay)}</select></div>
        <div class="tc-field"><label>Body font</label><select id="tcFontBody">${fontOpts(activeTheme.fontBody)}</select></div>
        <div class="tc-actions">
          <button id="tcReset">Reset</button>
          <button id="tcSave" class="primary">Save</button>
        </div>
      </div>`;

    const panel = $("#tcPanel");
    $("#tcToggle").addEventListener("click", () => panel.classList.toggle("open"));

    const read = () => ({
      primaryColor:   $("#tcPrimary").value,
      secondaryColor: $("#tcSecondary").value,
      accentColor:    $("#tcAccent").value,
      bgColor:        $("#tcBg").value,
      textColor:      $("#tcText").value,
      fontDisplay:    $("#tcFontDisplay").value,
      fontBody:       $("#tcFontBody").value
    });

    // Live preview on any change
    ["tcPrimary", "tcSecondary", "tcAccent", "tcBg", "tcText", "tcFontDisplay", "tcFontBody"].forEach((id) => {
      $("#" + id).addEventListener("input", () => applyTheme(read()));
    });

    $("#tcSave").addEventListener("click", () => {
      saveTheme(read());
      applyTheme(read());
      const btn = $("#tcSave");
      const orig = btn.textContent; btn.textContent = "Saved ✓";
      setTimeout(() => { btn.textContent = orig; panel.classList.remove("open"); }, 900);
    });

    $("#tcReset").addEventListener("click", () => {
      saveTheme({});
      applyTheme(cfg.theme);
      $("#tcPrimary").value = cfg.theme.primaryColor;
      $("#tcSecondary").value = cfg.theme.secondaryColor;
      $("#tcAccent").value = cfg.theme.accentColor;
      $("#tcBg").value = cfg.theme.bgColor;
      $("#tcText").value = cfg.theme.textColor;
      $("#tcFontDisplay").value = cfg.theme.fontDisplay;
      $("#tcFontBody").value = cfg.theme.fontBody;
    });
  }

  /* ------------------------------------------------------------------- BOOT */
  function init() {
    const activeTheme = Object.assign({}, cfg.theme, loadSavedTheme());
    applyTheme(activeTheme);
    applySeo(cfg.seo);
    applyFavicon(cfg.brand);
    applyContentOverrides();

    renderNav();
    renderHero();
    renderAbout();
    renderServices();
    renderSolutions();
    renderWhy();
    renderIndustries();
    renderProjects();
    renderPartners();
    renderTestimonials();
    renderContact();
    renderFooter();

    initInteractions();
    if (!window.HNC_PRODUCTION) buildThemeCustomizer(activeTheme);

    // Public API used by the optional content editor (editor.js)
    window.HNC = {
      cfg: cfg,
      loadContent: loadContent,
      saveContent: saveContent,
      refreshSection: refreshSection
    };
  }

  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", init);
  else init();
})();